function load_code(){

//CSS STYLE:
cCODESTRING = "";
cCODESTRING +="   *                                                                              ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	margin: 0;                                                                   ";
cCODESTRING +="   	padding: 0;                                                                  ";
cCODESTRING +="   	box-sizing: border-box;                                                      ";
cCODESTRING +="   	font-family: 'Poppins',sans-serif;                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section                                                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   position: relative;                                                            ";
cCODESTRING +="   width:100%;                                                                    ";
cCODESTRING +="   height: 100vh;                                                                 ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx                                                             ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   display: flex;                                                                 ";
cCODESTRING +="       justify-content: center;                                                   ";
cCODESTRING +="       width: 70%;                                                                ";
cCODESTRING +="       height: 90%;                                                               ";
cCODESTRING +="       z-index: 1;                                                                ";
cCODESTRING +="   	margin: auto;                                                                ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx                                                     ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	width: 50%;                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx h2                                                  ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 600;                                                            ";
cCODESTRING +="   	font-size: 1.5em;                                                            ";
cCODESTRING +="   	text-transform: uppercase;                                                   ";
cCODESTRING +="   	margin-bottom: 20px;                                                         ";
cCODESTRING +="   	margin-top: 50px;                                                            ";
cCODESTRING +="   	border-bottom: 4px solid #ff4584;                                            ";
cCODESTRING +="   	display: inline-block;                                                       ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx                                            ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="    margin-bottom: 20px;                                                          ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx span                                       ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	margin-bottom: 5px;                                                          ";
cCODESTRING +="   	display: inline-block;                                                       ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 16px;                                                           ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx input                                      ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	text-transform: uppercase;                                                   ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	padding: 10px 20px;                                                          ";
cCODESTRING +="   	outline: none;                                                               ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	border: 1px solid #607d8b;                                                   ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	background: transparent;                                                     ";
cCODESTRING +="   	border-radius: 10px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx img                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	                                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input                                ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	padding: 10px 20px;                                                          ";
cCODESTRING +="   	outline: none;                                                               ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	border: 1px solid #607d8b;                                                   ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	background: transparent;                                                     ";
cCODESTRING +="   	border-radius: 10px;                                                         ";
cCODESTRING +="   	background-color: beige;                                                     ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input[type=\"button\"] {               ";
cCODESTRING +="       background: #290850;                                                       ";
cCODESTRING +="       color: #fff;                                                               ";
cCODESTRING +="       outline: none;                                                             ";
cCODESTRING +="       border: none;                                                              ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="       cursor: pointer;                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input[type=\"button\"]:hover           ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #f53677;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx input[type=\"submit\"] {                     ";
cCODESTRING +="       background: #583285;                                                       ";
cCODESTRING +="       color: #fff;                                                               ";
cCODESTRING +="       outline: none;                                                             ";
cCODESTRING +="       border: none;                                                              ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="       cursor: pointer;                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx input[type=\"submit\"]:hover                 ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #f53677;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .remember                                           ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	margin-bottom: 10px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	font-size: 14px;                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx p                                          ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   color: #607d8b;                                                                ";
cCODESTRING +="   text-align: center;                                                            ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx p a                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   color: #ff4584;                                                                ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx h3 {                                                ";
cCODESTRING +="       color: #607d8b;                                                            ";
cCODESTRING +="       text-align: center;                                                        ";
cCODESTRING +="       margin: 26px 0 10px;                                                       ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci                                                ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	display: flex;                                                               ";
cCODESTRING +="   	justify-content: center;                                                     ";
cCODESTRING +="   	align-items: center;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li                                             ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	list-style: none;                                                            ";
cCODESTRING +="       width: 50px;                                                               ";
cCODESTRING +="   	height: 50px;                                                                ";
cCODESTRING +="   	display: flex;                                                               ";
cCODESTRING +="   	justify-content: center;                                                     ";
cCODESTRING +="   	align-items: center;                                                         ";
cCODESTRING +="   	background: #607d8b;                                                         ";
cCODESTRING +="   	border-radius: 50%;                                                          ";
cCODESTRING +="   	margin: 0 7px;                                                               ";
cCODESTRING +="   	cursor: pointer;                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li:hover                                       ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #ff4584;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li img                                         ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	transform: scale(0.5);                                                       ";
cCODESTRING +="   	filter: invert(1);                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   @media (max-width: 1000px)                                                     ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	section .contentBx {                                                         ";
cCODESTRING +="       display: flex;                                                             ";
cCODESTRING +="       justify-content: center;                                                   ";
cCODESTRING +="       width: 100%;                                                               ";
cCODESTRING +="       height: 90%;                                                               ";
cCODESTRING +="       z-index: 1;                                                                ";
cCODESTRING +="       margin: auto;                                                              ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   @media (max-width: 600px)                                                      ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	section .contentBx .formBx img                                               ";
cCODESTRING +="   	{                                                                            ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   	section .contentBx {                                                         ";
cCODESTRING +="   		display: flex;                                                           ";
cCODESTRING +="   		justify-content: center;                                                 ";
cCODESTRING +="   		align-items: center;                                                     ";
cCODESTRING +="   		width: 100%;                                                             ";
cCODESTRING +="   		height: 120%;                                                            ";
cCODESTRING +="   		z-index: 1;                                                              ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="   	section .contentBx .formBx                                                   ";
cCODESTRING +="   	{                                                                            ";
cCODESTRING +="   		width: 100%;                                                             ";
cCODESTRING +="   		padding: 40px;                                                           ";
cCODESTRING +="   		background: rgb(255 255 255 / 0.9);                                      ";
cCODESTRING +="   		margin: 20px;                                                            ";
cCODESTRING +="   		margin-top: auto;                                                        ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="   }                                                                              ";

//HTML BODY
codeHTML ="<head>";
codeHTML +="<link rel='icon' href='https://dl.dropboxusercontent.com/scl/fi/1sf3gvqxj92q676wbwzsd/lgu_virac_icon_16.ico?rlkey=8f1y89568lqs0m9m1f7uv3liy?a=1' type='image/x-icon'>";
codeHTML +="    <link rel='shortcut icon' href='https://dl.dropboxusercontent.com/scl/fi/1sf3gvqxj92q676wbwzsd/lgu_virac_icon_16.ico?rlkey=8f1y89568lqs0m9m1f7uv3liy?a=1' type='image/x-icon'>";
codeHTML +="    	<meta charset=\"UTF-8\">                                                                                           ";
codeHTML +="    	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">                                         ";
codeHTML +="     <title>BPLO - LGU Virac Business Permit Registration Portal</title>                                                                                 ";
codeHTML +="    </head>                                                                                                                ";
codeHTML +="                                                                                                                           "; 
codeHTML +="    <body>                                                                                                                 ";
codeHTML +="    	<section>                                                                                                          ";
codeHTML +="    	<form name=\"myform\">                                                                                             ";
codeHTML +="    		<div class=\"contentBx\">                                                                                      ";
codeHTML +="    			<div class=\"formBx\">                                                                                     ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class='inputBx'>                                                                              ";
codeHTML +="    						<img src=\"https://dl.dropbox.com/scl/fi/seyxm9bp2ethjyud00iv2/bplo_portal_header_img.jpg?rlkey=fbuk5x34r7s0gttj5hlutiodg\"></img>                                                           ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<h2 style='color: blue;text-align: center;' >BPLO - Business Permit Portal</h2><br>                                                            ";
codeHTML +="    					<p style='text-align: justify;' ><font color=white>- - - - -</font>Welcome! This portal is here to assist you in preparing your Business Application Form for both new registrations and renewals of your Business Establishment.<br><br><br></p>  ";
codeHTML +="                        <hr><br>";
codeHTML +="    					<div class=\"inputRegister\">                                                                      ";
codeHTML +="    								<input type=\"button\" style='text-align:left'  value=\"1 - Unified Application Form (UAF) - WalkIn (A4)\" name=\"\" onClick='open_pdf_link()' >            ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class=\"inputRegister\">                                                                      ";
codeHTML +="    								<input type=\"button\" style='text-align:left'  value=\"2 - PSA PSIC Search Engine (Line of Business)\" name=\"\" onClick='open_psa_link()' >            ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class=\"inputRegister\">                                                                      ";
codeHTML +="    								<input type=\"button\" style='text-align:left'  value=\"3 - iBPLS Online-Application\" name=\"\" onClick='open_dict_link()' >            ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class=\"inputRegister\">                                                                      ";
codeHTML +="    								<input type=\"button\" style='text-align:left'  value=\"4 - Application Process Guidelines and Notices\" name=\"\" onClick='guide_page()' >            ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<hr></hr>                                                                                          ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class='inputBx' hidden>                                                                              ";
codeHTML +="    						<span>TICKET NO.</span>                                                                      ";
codeHTML +="    						<input type='text' id='ticket_no' value=''>                                                  ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<div class='inputBx' hidden>                                                                              ";
codeHTML +="    						<span>DISTRICT NO.</span>                                                                      ";
codeHTML +="    						<input type='text' id='district_no' value=''>                                                  ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<div class='inputBx' hidden>                                                                              ";
codeHTML +="    						<span>BARANGAY</span>                                                                          ";
codeHTML +="    						<input type='text' id='barangay' value=''>                                                     ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<div class='inputBx' hidden>                                                                              ";
codeHTML +="    						<span>FULLNAME</span>                                                                          ";
codeHTML +="    						<input type='text' id='fullname' value=''>                                                     ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<div class='inputBx' hidden>                                                                              ";
codeHTML +="    						<span>PRICE</span>                                                                             ";
codeHTML +="    						<input type='text' id='myprice' value=''>                                                      ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br>                                                                                               ";

codeHTML +="    					<p style='font-size: 12px'><b>For more info, contact us at BPLO Official Email:</b> <i>bplo.lgu.virac.369@gmail.com</i><br><b>Powered by</b> <u>BPLO IT 2024</u></p>                                                          ";
codeHTML +="<br><br><br>";
codeHTML +="    			</div>                                                                                                     ";
codeHTML +="    		</div>                                                                                                         ";
codeHTML +="    	</form>	                                                                                                           ";
codeHTML +="    	</section>                                                                                                         ";
codeHTML +="    </body>                                                                                                                ";
document.body.style.zoom = "100%";
document.body.style.visibility = "visible";


document.body.innerHTML = "<style>" +cCODESTRING+"</style>"+codeHTML;
//location.reload();

}
load_code();

function open_psa_link(){
linker = "https://psa.gov.ph/classification/psic/subclass";
window.open(linker,'_new');
}

function open_dict_link(){
linker = "https://prod9.ebpls.com/viraccatanduanes/index.php/login";
window.open(linker,'_new');
}

function open_pdf_link(){
linker = "https://dl.dropbox.com/scl/fi/rncl5uz48v811w8nr3txm/UAF-Unified-Application-Form.PDF?rlkey=ybmb61c7z40mp4jvtyrtp3r5l";
window.open(linker,'_new');
}


function guide_page(){
cCODESTRING = "";
cCODESTRING +="   *                                                                              ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	margin: 0;                                                                   ";
cCODESTRING +="   	padding: 0;                                                                  ";
cCODESTRING +="   	box-sizing: border-box;                                                      ";
cCODESTRING +="   	font-family: 'Poppins',sans-serif;                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section                                                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   position: relative;                                                            ";
cCODESTRING +="   width:100%;                                                                    ";
cCODESTRING +="   height: 100vh;                                                                 ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx                                                             ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   display: flex;                                                                 ";
cCODESTRING +="       justify-content: center;                                                   ";
cCODESTRING +="       width: 70%;                                                                ";
cCODESTRING +="       height: 90%;                                                               ";
cCODESTRING +="       z-index: 1;                                                                ";
cCODESTRING +="   	margin: auto;                                                                ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx                                                     ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	width: 50%;                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx h2                                                  ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 600;                                                            ";
cCODESTRING +="   	font-size: 1.5em;                                                            ";
cCODESTRING +="   	text-transform: uppercase;                                                   ";
cCODESTRING +="   	margin-bottom: 20px;                                                         ";
cCODESTRING +="   	margin-top: 50px;                                                            ";
cCODESTRING +="   	border-bottom: 4px solid #ff4584;                                            ";
cCODESTRING +="   	display: inline-block;                                                       ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx                                            ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="    margin-bottom: 20px;                                                          ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx span                                       ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	margin-bottom: 5px;                                                          ";
cCODESTRING +="   	display: inline-block;                                                       ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 16px;                                                           ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx input                                      ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	text-transform: uppercase;                                                   ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	padding: 10px 20px;                                                          ";
cCODESTRING +="   	outline: none;                                                               ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	border: 1px solid #607d8b;                                                   ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	background: transparent;                                                     ";
cCODESTRING +="   	border-radius: 10px;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx img                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	                                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input                                ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	padding: 10px 20px;                                                          ";
cCODESTRING +="   	outline: none;                                                               ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	border: 1px solid #607d8b;                                                   ";
cCODESTRING +="   	font-size: 16px;                                                             ";
cCODESTRING +="   	letter-spacing: 1px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	background: transparent;                                                     ";
cCODESTRING +="   	border-radius: 10px;                                                         ";
cCODESTRING +="   	background-color: beige;                                                     ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input[type=\"button\"] {               ";
cCODESTRING +="       background: #290850;                                                       ";
cCODESTRING +="       color: #fff;                                                               ";
cCODESTRING +="       outline: none;                                                             ";
cCODESTRING +="       border: none;                                                              ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="       cursor: pointer;                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputRegister input[type=\"button\"]:hover           ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #f53677;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   section .contentBx .formBx .inputBx input[type=\"submit\"] {                     ";
cCODESTRING +="       background: #583285;                                                       ";
cCODESTRING +="       color: #fff;                                                               ";
cCODESTRING +="       outline: none;                                                             ";
cCODESTRING +="       border: none;                                                              ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="       cursor: pointer;                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx input[type=\"submit\"]:hover                 ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #f53677;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .remember                                           ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	margin-bottom: 10px;                                                         ";
cCODESTRING +="   	color: #607d8b;                                                              ";
cCODESTRING +="   	font-weight: 400;                                                            ";
cCODESTRING +="   	font-size: 14px;                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx p                                          ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   color: #607d8b;                                                                ";
cCODESTRING +="   text-align: center;                                                            ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .inputBx p a                                        ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   color: #ff4584;                                                                ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx h3 {                                                ";
cCODESTRING +="       color: #607d8b;                                                            ";
cCODESTRING +="       text-align: center;                                                        ";
cCODESTRING +="       margin: 26px 0 10px;                                                       ";
cCODESTRING +="       font-weight: 500;                                                          ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci                                                ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	display: flex;                                                               ";
cCODESTRING +="   	justify-content: center;                                                     ";
cCODESTRING +="   	align-items: center;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li                                             ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	list-style: none;                                                            ";
cCODESTRING +="       width: 50px;                                                               ";
cCODESTRING +="   	height: 50px;                                                                ";
cCODESTRING +="   	display: flex;                                                               ";
cCODESTRING +="   	justify-content: center;                                                     ";
cCODESTRING +="   	align-items: center;                                                         ";
cCODESTRING +="   	background: #607d8b;                                                         ";
cCODESTRING +="   	border-radius: 50%;                                                          ";
cCODESTRING +="   	margin: 0 7px;                                                               ";
cCODESTRING +="   	cursor: pointer;                                                             ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li:hover                                       ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	background: #ff4584;                                                         ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   section .contentBx .formBx .sci li img                                         ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	transform: scale(0.5);                                                       ";
cCODESTRING +="   	filter: invert(1);                                                           ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   @media (max-width: 1000px)                                                     ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	section .contentBx {                                                         ";
cCODESTRING +="       display: flex;                                                             ";
cCODESTRING +="       justify-content: center;                                                   ";
cCODESTRING +="       width: 100%;                                                               ";
cCODESTRING +="       height: 90%;                                                               ";
cCODESTRING +="       z-index: 1;                                                                ";
cCODESTRING +="       margin: auto;                                                              ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   }                                                                              ";
cCODESTRING +="   @media (max-width: 600px)                                                      ";
cCODESTRING +="   {                                                                              ";
cCODESTRING +="   	section .contentBx .formBx img                                               ";
cCODESTRING +="   	{                                                                            ";
cCODESTRING +="   	width: 100%;                                                                 ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="                                                                                  ";
cCODESTRING +="   	section .contentBx {                                                         ";
cCODESTRING +="   		display: flex;                                                           ";
cCODESTRING +="   		justify-content: center;                                                 ";
cCODESTRING +="   		align-items: center;                                                     ";
cCODESTRING +="   		width: 100%;                                                             ";
cCODESTRING +="   		height: 120%;                                                            ";
cCODESTRING +="   		z-index: 1;                                                              ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="   	section .contentBx .formBx                                                   ";
cCODESTRING +="   	{                                                                            ";
cCODESTRING +="   		width: 100%;                                                             ";
cCODESTRING +="   		padding: 40px;                                                           ";
cCODESTRING +="   		background: rgb(255 255 255 / 0.9);                                      ";
cCODESTRING +="   		margin: 20px;                                                            ";
cCODESTRING +="   		margin-top: auto;                                                        ";
cCODESTRING +="   	}                                                                            ";
cCODESTRING +="   }                                                                              ";

//HTML BODY
codeHTML ="<head>";
codeHTML +="<link rel='icon' href='https://dl.dropboxusercontent.com/scl/fi/1sf3gvqxj92q676wbwzsd/lgu_virac_icon_16.ico?rlkey=8f1y89568lqs0m9m1f7uv3liy?a=1' type='image/x-icon'>";
codeHTML +="    <link rel='shortcut icon' href='https://dl.dropboxusercontent.com/scl/fi/1sf3gvqxj92q676wbwzsd/lgu_virac_icon_16.ico?rlkey=8f1y89568lqs0m9m1f7uv3liy?a=1' type='image/x-icon'>";
codeHTML +="    	<meta charset=\"UTF-8\">                                                                                           ";
codeHTML +="    	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">                                         ";
codeHTML +="     <title>BPLO - LGU Virac Business Permit Registration Portal</title>                                                                                 ";
codeHTML +="    </head>                                                                                                                ";
codeHTML +="                                                                                                                           "; 
codeHTML +="    <body>                                                                                                                 ";
codeHTML +="    	<section>                                                                                                          ";
codeHTML +="    	<form name=\"myform\">                                                                                             ";
codeHTML +="    		<div class=\"contentBx\">                                                                                      ";
codeHTML +="    			<div class=\"formBx\">                                                                                     ";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class='inputBx'>                                                                              ";
codeHTML +="    						<img src=\"https://dl.dropbox.com/scl/fi/seyxm9bp2ethjyud00iv2/bplo_portal_header_img.jpg?rlkey=fbuk5x34r7s0gttj5hlutiodg\"></img>                                                           ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<h2 style='color: blue;text-align: center; font-size: 16px' >BPLO - Application Process Guidelines and Notice</h2><br>                                                            ";
codeHTML +="    					<p style='text-align: justify;' ><font color=white>- - - - -</font>We extend a warm welcome to all clients embarking on the registration of their business permits, whether for new ventures or renewals. It is with great importance that we present to you these guidelines and notices, which are pivotal in ensuring a streamlined and efficient application process. Following these instructions diligently is imperative to circumvent any potential delays or complications in your application.<br><br><br></p>  ";
codeHTML +="                        <hr><br>";
codeHTML +="    					<p style='text-align: justify;' ><b>A - When completing the Business Application Form</b>, it is imperative that the business name provided aligns precisely with the official records registered with the Department of Trade and Industry (DTI), Securities and Exchange Commission (SEC), or Cooperative Development Authority (CDA) certification.";
codeHTML +="                        <br>";
codeHTML +="                        <hr><br>";
codeHTML +="    					<p style='text-align: justify;' ><b>B - In the section dedicated to the Line of Business</b>, it is essential that you reference the Philippine Standard Industry Classification (PSIC) list. The PSIC code and the corresponding line of business description should accurately correspond to the nature of your business enterprise.";
codeHTML +="                        <br>";
codeHTML +="                        <hr><br>";
codeHTML +="    					<p style='text-align: justify;' ><b>C - To expedite the application process</b>, we kindly request that you submit only the documents explicitly required. Extraneous or superfluous documents should be omitted, as their inclusion may lead to unnecessary complications.";
codeHTML +="                        <br>";
codeHTML +="                        <hr><br>";
codeHTML +="    					<p style='text-align: justify;' ><b>D - Lastly</b>, it is crucial to ensure that your application includes a declaration of capitalization for new businesses or gross sales receipts for renewal applications. This information is vital for the accurate assessment of your business permit.";
codeHTML +="                        <br>";
codeHTML +="                        <hr><br><br><br>";
codeHTML +="    					<p style='text-align: justify;' >We are committed to providing you with the utmost support and guidance throughout your application process. By adhering to these guidelines, you contribute to a more efficient and effective process, ultimately enabling the timely approval of your business permit.";
codeHTML +="                        <br>";
codeHTML +="    					<br>                                                                                               ";
codeHTML +="    					<div class=\"inputRegister\">                                                                      ";
codeHTML +="    								<input type=\"button\" style='text-align:center'  value=\"BACK\" name=\"\" onClick='load_code()' >            ";
codeHTML +="    					</div>                                                                                             ";
codeHTML +="    					<br><br><br><br>                                                                                             ";

codeHTML +="    			</div>                                                                                                     ";
codeHTML +="    		</div>                                                                                                         ";
codeHTML +="    	</form>	                                                                                                           ";
codeHTML +="    	</section>                                                                                                         ";
codeHTML +="    </body>                                                                                                                ";
document.body.style.zoom = "100%";
document.body.style.visibility = "visible";
document.body.innerHTML = "<style>" +cCODESTRING+"</style>"+codeHTML;
}
load_code();
